package com.doerit.dao;

import com.doerit.model.Employee;
import com.doerit.model.EmployeeExample;


import com.doerit.model.fullEmployeeDetails;
import com.doerit.util.Pager;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import java.util.ArrayList;
import java.util.List;

import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;

public interface EmployeeMapper {
	
	int countByExample1(EmployeeExample example);
    int deleteByExample1(EmployeeExample example);
//    int updateByPrimaryKeySelective(EmployeeExample record);
    
  
	@Select("SELECT c.ID,c.NIC,c.USER_ROLE,c.TITLE,c.FIRST_NAME ,U.STATUS" + 
    		" FROM tbl_employee AS c JOIN tbl_user_account AS U ON U.RELATION_ID = c.ID  COLLATE utf8_unicode_ci " + 
    		" ORDER BY c.ID  " +
    		" LIMIT #{pager.start}, #{pager.limit}")
    @ResultMap("BaseResultMap")
	List <fullEmployeeDetails> viewAllByStatus(@Param("pager")Pager pager,  @Param("status")byte status);
	
	
	
	
	@Select("SELECT count(0) " + 
    		" FROM tbl_employee c ")
	Integer countAllByStatus(@Param("status")byte status);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int countByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int deleteByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int insertSelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    List<Employee> selectByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    Employee selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int updateByExampleSelective(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int updateByExample(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int updateByPrimaryKeySelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    
    int updateByPrimaryKey(Employee record);
    
    
}